version: '3.8'

services:
  sqlserver_container:
    image: mcr.microsoft.com/mssql/server:2022-latest
    container_name: sqlserver_container
    ports:
      - "1433:1433"
    environment:
      SA_PASSWORD: "TaskFlow@123"
      ACCEPT_EULA: "Y"
    restart: always
    networks:
      - taskflow-network

  backend:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: taskflow_api
    ports:
      - "8080:8080"
    environment:
      ConnectionStrings__SqlServer: "Server=sqlserver_container;Database=TaskFlow;User Id=taskflow_user;Password=TaskFlow@123;TrustServerCertificate=True;"
    depends_on:
      - sqlserver_container
    networks:
      - taskflow-network

networks:
  taskflow-network:
    driver: bridge
